inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - db/schema.rb
    - bin/**/*
  NewCops: enable
Style/Documentation:
  Enabled: false
Rails/EnvironmentVariableAccess:
  AllowReads: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application
